name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: |
          cd app
          ./gradlew build

      - name: Run setup and tests
        run: |
          cd app
          make setup
          make lint
          make test

      - name: Generate JaCoCo Test Report
        run: |
          cd app
          ./gradlew jacocoTestReport

      - name: Verify JaCoCo report exists
        run: |
          ls -l app/build/reports/jacoco/test/jacocoTestReport.xml

      - name: Verify test.html exists
        run: |
          ls -l app/src/test/resources/test.html

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          JACOCO_SOURCE_PATH: app/src/main/java
        with:
          coverageCommand: make report
          coverageLocations: ${{ github.workspace }}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
